server:
  port: ${PORT:5000}
  servlet:
    context-path: /

# Sentry Environment Variables
sentry-config:
  sentry-dsn: ${SENTRY_DSN}

  jpa:
    # 'spring.jpa.open-in-view' is enabled by default.
    # Therefore, database queries may be performed during view rendering.
    # Explicitly configure spring.jpa.open-in-view to disable this warning
    open-in-view: false

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB