server:
  port: ${PORT:5000}
  servlet:
    context-path: /

# Sentry Environment Variables
sentry-config:
  sentry-dsn: ${SENTRY_DSN}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB